"""
Report Agent
=============
Specialized in generating professional security reports.

Generates:
- Executive summary (non-technical)
- Technical findings with PoCs
- Remediation recommendations
- CVSS scoring
- OWASP mapping
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional


@dataclass
class ReportConfig:
    """Report generation configuration."""
    title: str = "Security Assessment Report"
    client_name: str = ""
    assessor_name: str = ""
    assessment_type: str = "blackbox"  # "blackbox", "whitebox", "greybox"
    scope: str = ""
    executive_summary: bool = True
    technical_details: bool = True
    remediation: bool = True
    appendices: bool = True
    format: str = "markdown"  # "markdown", "html", "json"


class ReportAgent:
    """
    Report generation agent.
    
    Usage:
        agent = ReportAgent()
        report = agent.generate_full_report(
            config=ReportConfig(title="Q2 Pentest"),
            recon_results=recon,
            analysis_results=analysis,
            exploit_results=exploits,
            chains=chains,
        )
    """
    
    def generate_full_report(
        self,
        config: ReportConfig,
        recon_results=None,
        analysis_results=None,
        exploit_results=None,
        chains=None,
        race_results=None,
        logic_results=None,
    ) -> str:
        """Generate a comprehensive security report."""
        
        report = f"""# 🔒 {config.title}

**Client:** {config.client_name or 'Confidential'}
**Assessor:** {config.assessor_name or 'Strix-Advanced'}
**Date:** {datetime.utcnow().strftime('%Y-%m-%d')}
**Type:** {config.assessment_type.upper()}
**Scope:** {config.scope or 'Full application'}

---

"""
        
        # Executive Summary
        if config.executive_summary:
            report += self._generate_executive_summary(
                analysis_results, exploit_results, chains
            )
        
        # Findings Summary
        report += self._generate_findings_summary(
            analysis_results, exploit_results, race_results, logic_results
        )
        
        # Exploit Chains
        if chains:
            report += "\n# 🔗 Exploit Chains\n\n"
            for chain in chains:
                report += f"## {chain.name}\n"
                report += f"**Severity:** {chain.combined_severity.upper()} | **CVSS:** {chain.cvss_estimate}\n"
                report += f"**Impact:** {chain.combined_impact}\n\n"
                report += "### Chain Steps\n"
                for i, step in enumerate(chain.steps, 1):
                    report += f"{i}. {step.vuln_type}: {step.title}\n"
                report += "\n---\n\n"
        
        # Technical Findings
        if config.technical_details and analysis_results:
            report += "\n# 🔍 Technical Findings\n\n"
            for finding in (analysis_results.findings if hasattr(analysis_results, 'findings') else []):
                report += finding.to_markdown()
                report += "\n---\n\n"
        
        # Exploit Results
        if exploit_results:
            report += "\n# 💥 Exploitation Results\n\n"
            for result in (exploit_results if isinstance(exploit_results, list) else []):
                if hasattr(result, 'exploited') and result.exploited:
                    report += f"""## {result.vuln_type.upper()} — Exploited ✅

**Target:** {result.target}
**Severity:** {result.severity.upper()}

### PoC
```
{result.poc_code}
```

### Steps
"""
                    for step in result.poc_steps:
                        report += f"- {step}\n"
                    
                    report += f"""
### Impact
{result.impact}

### Remediation
{result.remediation}

---
"""
        
        # Race Conditions
        if race_results:
            report += "\n# 🏃 Race Conditions\n\n"
            for result in race_results:
                if hasattr(result, 'race_detected') and result.race_detected:
                    report += f"## {result.test_name}\n"
                    report += f"**URL:** {result.url}\n"
                    report += f"**Successful:** {result.successful_requests}/{result.total_requests}\n"
                    report += f"**Severity:** {result.severity}\n\n"
        
        # Recon
        if recon_results:
            report += "\n# 🔍 Reconnaissance\n\n"
            if hasattr(recon_results, 'subdomains'):
                report += f"**Subdomains:** {len(recon_results.subdomains)}\n"
                for sub in recon_results.subdomains[:20]:
                    report += f"- {sub}\n"
            if hasattr(recon_results, 'technologies'):
                report += f"\n**Technologies:** {', '.join(recon_results.technologies)}\n"
        
        report += f"""

---

*Report generated by Strix-Advanced on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*
"""
        
        return report
    
    def _generate_executive_summary(self, analysis, exploits, chains) -> str:
        """Generate non-technical executive summary."""
        total_findings = 0
        critical = 0
        high = 0
        
        if analysis and hasattr(analysis, 'findings'):
            total_findings = len(analysis.findings)
            critical = sum(1 for f in analysis.findings if f.severity.value == "critical")
            high = sum(1 for f in analysis.findings if f.severity.value == "high")
        
        chain_count = len(chains) if chains else 0
        
        summary = f"""# 📋 Executive Summary

A security assessment was conducted to identify vulnerabilities and security weaknesses in the target application. The assessment included static code analysis, dynamic testing, and exploitation attempts.

## Key Findings

| Metric | Value |
|--------|-------|
| Total Vulnerabilities | {total_findings} |
| Critical | {critical} |
| High | {high} |
| Exploit Chains | {chain_count} |

## Risk Assessment

"""
        
        if critical > 0:
            summary += "**Overall Risk: CRITICAL** — Immediate remediation required.\n\n"
            summary += f"There are {critical} critical vulnerabilities that could lead to full system compromise, data breach, or financial loss. These should be addressed immediately.\n"
        elif high > 0:
            summary += "**Overall Risk: HIGH** — Prompt remediation recommended.\n\n"
            summary += f"There are {high} high-severity vulnerabilities that could lead to significant security impact. These should be addressed within the current sprint.\n"
        else:
            summary += "**Overall Risk: LOW to MEDIUM** — Standard remediation timeline.\n"
        
        summary += "\n---\n\n"
        
        return summary
    
    def _generate_findings_summary(self, analysis, exploits, race, logic) -> str:
        """Generate findings summary table."""
        summary = """# 📊 Findings Summary

| # | Type | Severity | Status |
|---|------|----------|--------|
"""
        
        idx = 1
        
        if analysis and hasattr(analysis, 'findings'):
            for finding in analysis.findings:
                summary += f"| {idx} | {finding.vuln_type} | {finding.severity.value.upper()} | Found |\n"
                idx += 1
        
        if exploits:
            for result in (exploits if isinstance(exploits, list) else []):
                if hasattr(result, 'exploited') and result.exploited:
                    summary += f"| {idx} | {result.vuln_type} | {result.severity.upper()} | Exploited |\n"
                    idx += 1
        
        if race:
            for result in race:
                if hasattr(result, 'race_detected') and result.race_detected:
                    summary += f"| {idx} | Race Condition | {result.severity.upper()} | Exploited |\n"
                    idx += 1
        
        summary += "\n---\n\n"
        
        return summary
